In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
#p1 dataset
plant_1 = pd.read_csv('plant1.csv')

In [3]:
plant_1.describe()

,dc_power,ac_power,daily_yield,total_yield,ambient_temperature,module_temperature,irradiation
count,68774.000000,68774.000000,68774.000000,6.877400e+04,68774.000000,68774.000000,68774.000000
mean,314.717745,307.778375,3501.254124,6.978728e+06,25.558521,31.244997,0.232305
std,403.644183,394.394865,3169.832450,4.162707e+05,3.361300,12.308283,0.301948
min,0.000000,0.000000,0.000000,6.183645e+06,20.398505,18.140415,0.000000
25%,0.000000,0.000000,0.584821,6.512007e+06,22.724491,21.123944,0.000000
50%,42.857143,41.450000,3298.785714,7.146685e+06,24.670178,24.818984,0.031620
75%,636.546875,623.561161,6448.714286,7.268751e+06,27.960429,41.693659,0.454880
max,1447.112500,1410.950000,9163.000000,7.846821e+06,35.252486,65.545714,1.221652

In [4]:
plant_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68774 entries, 0 to 68773
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date_time            68774 non-null  object
 1   source_key_x         68774 non-null  object
 2   dc_power             68774 non-null  float64
 3   ac_power             68774 non-null  float64
 4   daily_yield          68774 non-null  float64
 5   total_yield          68774 non-null  float64
 6   ambient_temperature  68774 non-null  float64
 7   module_temperature   68774 non-null  float64
 8   irradiation          68774 non-null  float64
dtypes: float64(7), object(2)
memory usage: 4.7+ MB

In [5]:
plant_1 = pd.get_dummies(plant_1, columns=['source_key_x'])
plant_1

,date_time,dc_power,ac_power,daily_yield,total_yield,ambient_temperature,module_temperature,irradiation,source_key_x_1BY6WEcLGh8j5v7,source_key_x_1IF53ai7Xc0U56Y,...,source_key_x_iCRJl6heRkivqQ3,source_key_x_ih0vzX44oOqAx2f,source_key_x_pkci93gMrogZuBj,source_key_x_rGa61gmuvPhdLxV,source_key_x_sjndEbLyjtCKgGv,source_key_x_uHbuxQJl8lW7ozc,source_key_x_wCURE6d3bPkepu2,source_key_x_z9Y9gH1T5YWrNuG,source_key_x_zBIq5rxdHJRwDNY,source_key_x_zVJPv84UY57bAof
0,2020-05-15 00:00:00,0.0,0.0,0.000,6259559.0,25.184316,22.857507,0.0,True,False,...,False,False,False,False,False,False,False,False,False,False
1,2020-05-15 00:00:00,0.0,0.0,0.000,6183645.0,25.184316,22.857507,0.0,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2020-05-15 00:00:00,0.0,0.0,0.000,6987759.0,25.184316,22.857507,0.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2020-05-15 00:00:00,0.0,0.0,0.000,7602960.0,25.184316,22.857507,0.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2020-05-15 00:00:00,0.0,0.0,0.000,7158964.0,25.184316,22.857507,0.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68769,2020-06-17 23:45:00,0.0,0.0,5967.000,7287002.0,21.909288,20.427972,0.0,False,False,...,False,False,False,False,False,True,False,False,False,False
68770,2020-06-17 23:45:00,0.0,0.0,5147.625,7028601.0,21.909288,20.427972,0.0,False,False,...,False,False,False,False,False,False,True,False,False,False
68771,2020-06-17 23:45:00,0.0,0.0,5819.000,7251204.0,21.909288,20.427972,0.0,False,False,...,False,False,False,False,False,False,False,True,False,False
68772,2020-06-17 23:45:00,0.0,0.0,5817.000,6583369.0,21.909288,20.427972,0.0,False,False,...,False,False,False,False,False,False,False,False,True,False
68773,2020-06-17 23:45:00,0.0,0.0,5910.000,7363272.0,21.909288,20.427972,0.0,False,False,...,False,False,False,False,False,False,False,False,False,True

In [6]:
plant_1 = plant_1.applymap(lambda x: 1 if x is True else 0 if x is False else x)
plant_1

C:\Users\loris\AppData\Local\Temp\ipykernel_2540\3266294516.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  plant_1 = plant_1.applymap(lambda x: 1 if x is True else 0 if x is False else x)

,date_time,dc_power,ac_power,daily_yield,total_yield,ambient_temperature,module_temperature,irradiation,source_key_x_1BY6WEcLGh8j5v7,source_key_x_1IF53ai7Xc0U56Y,...,source_key_x_iCRJl6heRkivqQ3,source_key_x_ih0vzX44oOqAx2f,source_key_x_pkci93gMrogZuBj,source_key_x_rGa61gmuvPhdLxV,source_key_x_sjndEbLyjtCKgGv,source_key_x_uHbuxQJl8lW7ozc,source_key_x_wCURE6d3bPkepu2,source_key_x_z9Y9gH1T5YWrNuG,source_key_x_zBIq5rxdHJRwDNY,source_key_x_zVJPv84UY57bAof
0,2020-05-15 00:00:00,0.0,0.0,0.000,6259559.0,25.184316,22.857507,0.0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-05-15 00:00:00,0.0,0.0,0.000,6183645.0,25.184316,22.857507,0.0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2020-05-15 00:00:00,0.0,0.0,0.000,6987759.0,25.184316,22.857507,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-05-15 00:00:00,0.0,0.0,0.000,7602960.0,25.184316,22.857507,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-05-15 00:00:00,0.0,0.0,0.000,7158964.0,25.184316,22.857507,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68769,2020-06-17 23:45:00,0.0,0.0,5967.000,7287002.0,21.909288,20.427972,0.0,0,0,...,0,0,0,0,0,1,0,0,0,0
68770,2020-06-17 23:45:00,0.0,0.0,5147.625,7028601.0,21.909288,20.427972,0.0,0,0,...,0,0,0,0,0,0,1,0,0,0
68771,2020-06-17 23:45:00,0.0,0.0,5819.000,7251204.0,21.909288,20.427972,0.0,0,0,...,0,0,0,0,0,0,0,1,0,0
68772,2020-06-17 23:45:00,0.0,0.0,5817.000,6583369.0,21.909288,20.427972,0.0,0,0,...,0,0,0,0,0,0,0,0,1,0
68773,2020-06-17 23:45:00,0.0,0.0,5910.000,7363272.0,21.909288,20.427972,0.0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
plant_1['date_time'] = pd.to_datetime(plant_1['date_time'])

In [8]:
plant_1[1000:1100]

,date_time,dc_power,ac_power,daily_yield,total_yield,ambient_temperature,module_temperature,irradiation,source_key_x_1BY6WEcLGh8j5v7,source_key_x_1IF53ai7Xc0U56Y,...,source_key_x_iCRJl6heRkivqQ3,source_key_x_ih0vzX44oOqAx2f,source_key_x_pkci93gMrogZuBj,source_key_x_rGa61gmuvPhdLxV,source_key_x_sjndEbLyjtCKgGv,source_key_x_uHbuxQJl8lW7ozc,source_key_x_wCURE6d3bPkepu2,source_key_x_z9Y9gH1T5YWrNuG,source_key_x_zBIq5rxdHJRwDNY,source_key_x_zVJPv84UY57bAof
1000,2020-05-15 11:30:00,690.457143,676.071429,2281.142857,6524453.143,30.287073,49.841364,0.557069,0,0,...,0,0,0,0,0,0,0,0,0,0
1001,2020-05-15 11:30:00,728.512500,712.775000,2355.875000,7100454.875,30.287073,49.841364,0.557069,0,0,...,0,0,0,0,0,0,0,0,0,0
1002,2020-05-15 11:30:00,808.385714,790.200000,2365.142857,6273720.143,30.287073,49.841364,0.557069,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,2020-05-15 11:30:00,735.312500,719.062500,2024.375000,6318827.375,30.287073,49.841364,0.557069,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2020-05-15 11:30:00,706.028571,690.757143,2502.428571,7180494.429,30.287073,49.841364,0.557069,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,2020-05-15 12:30:00,812.412500,794.675000,3218.750000,7114711.750,32.147685,52.353255,0.649248,0,0,...,0,0,0,1,0,0,0,0,0,0
1096,2020-05-15 12:30:00,800.471429,782.557143,3254.285714,7020086.286,32.147685,52.353255,0.649248,0,0,...,0,0,0,0,1,0,0,0,0,0
1097,2020-05-15 12:30:00,839.800000,821.200000,3270.571429,7041951.571,32.147685,52.353255,0.649248,0,0,...,0,0,0,0,0,1,0,0,0,0
1098,2020-05-15 12:30:00,944.812500,923.287500,3214.125000,6785812.125,32.147685,52.353255,0.649248,0,0,...,0,0,0,0,0,0,1,0,0,0
1099,2020-05-15 12:30:00,931.100000,909.875000,3283.500000,7011149.500,32.147685,52.353255,0.649248,0,0,...,0,0,0,0,0,0,0,1,0,0

In [9]:
plant_1a = plant_1.copy()

In [10]:
plant_1a['date_time'] = plant_1a['date_time'].apply(lambda x: x.timestamp())

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

# LINEAR REGRESSIONS

REGRESSIONE NORMALE

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


# Separazione delle caratteristiche (X) e della variabile target (y)
X = plant_1a.drop('daily_yield', axis=1)
y = plant_1a['daily_yield']

# Divisione del dataset in set di addestramento e test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creazione e addestramento del modello di regressione lineare
model = LinearRegression()
model.fit(X_train, y_train)

# Previsione sul set di test
y_pred = model.predict(X_test)

# Valutazione delle prestazioni del modello
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE:", mse)
print("R^2:", r2)

MSE: 5418855.676950639
R^2: 0.4600814619593966

REGRESSIONE K-FOLD 10

In [13]:
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_predict

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# Inizializza il modello di regressione
model = LinearRegression()

# Inizializza la cross-validation KFold
kf = KFold(n_splits=10, shuffle=True, random_state=1)

# Esegui la cross-validation sul training set
cv_scores = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=kf)

# Calcola la media e la deviazione standard dell'errore quadratico medio (MSE) della cross-validation
cv_mse_scores = -cv_scores
mean_cv_mse = cv_mse_scores.mean()
std_cv_mse = cv_mse_scores.std()

# Allena il modello sul training set completo
model.fit(X_train, y_train)

# Valuta il modello sul test set
y_pred = model.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred)

# Esegui la cross-validation per ottenere le previsioni su tutto il dataset
y_pred_cv = cross_val_predict(model, X, y, cv=kf)
# Calcola il coefficiente di determinazione (R²) utilizzando le previsioni della cross-validation
r2_cv = r2_score(y, y_pred_cv)

print(f'R^2 Score from Cross-Validation: {r2_cv}')
print(f'Mean CV MSE: {mean_cv_mse}')
print(f'Standard Deviation of CV MSE: {std_cv_mse}')
print(f'Test MSE: {test_mse}')

R^2 Score from Cross-Validation: 0.4761754419607328
Mean CV MSE: 5274832.974050746
Standard Deviation of CV MSE: 109413.45082501219
Test MSE: 5221572.429886162

LASSO REGRESSION

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error, r2_score

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creazione del modello di regressione Lasso
lasso = Lasso(alpha=0.1)  # Puoi regolare il valore di alpha per controllare la quantità di regolarizzazione

# Addestramento del modello
lasso.fit(X_train, y_train)

# Previsione sul set di test
y_pred = lasso.predict(X_test)

# Valutazione delle prestazioni del modello
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE:", mse)
print("R^2:", r2)

MSE: 5661452.096439231
R^2: 0.43590988184123536

C:\Users\loris\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.544e+11, tolerance: 5.530e+07
  model = cd_fast.enet_coordinate_descent(